Parcial-2/AppUsabilidad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomeApp.urls')),
    path('auth/', include('AuthApp.urls')),
    path('tienda/', include('TiendaApp.urls')),
]

#404 Page not found
handler404 = 'HomeApp.views.error_404_view'

Parcial-2/AuthApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name="login"),
    path('register/', views.register, name="register"),
]

Parcial-2/HomeApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home")
]

Parcial-2/TiendaApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('producto/<int:id>', views.producto, name='producto'), #url: /producto/1
    path('categoria/<int:id>', views.categoria, name='categoria') #url: /categoria/1
]

Parcial-2/AuthApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Persona(models.Model):
    Nombre = models.CharField(max_length=50)
    Apellido = models.CharField(max_length=50)
    Cedula = models.CharField(max_length=10)
    Email = models.EmailField(max_length=100)
    Usuario = models.OneToOneField(User, on_delete=models.CASCADE)

Parcial-2/HomeApp/models.py
from django.db import models

# Create your models here.

Parcial-2/TiendaApp/models.py
from django.db import models

# vamos a crear el modelo de categorias, productos e imagenes
# las categorias contaran con un titulo y una lista de productos
# los productos contaran con un nombre, precio, descripcion y una lista de imagenes
# las imagenes contaran con una url y un texto alternativo

# Create your models here.
class imagenProducto(models.Model):
    url = models.CharField(max_length=200)
    alt = models.CharField(max_length=200)

    def __str__(self):
        return self.alt
    
class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    precio = models.IntegerField()
    descripcion = models.CharField(max_length=200)
    imagenes = models.ManyToManyField(imagenProducto)

    def __str__(self):
        return self.nombre
    
class Categoria(models.Model):
    titulo = models.CharField(max_length=200)
    productos = models.ManyToManyField(Producto)

    def __str__(self):
        return self.titulo

Parcial-2/AuthApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login
from .models import Persona

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('tienda')
    error_message = None
    if request.method == 'POST':
        Usuario = request.POST['username']
        Password = request.POST['password']
        
        print(Usuario, Password)
        
        user = authenticate(request, username=Usuario, password=Password)
        
        if user is not None:
            auth_login(request, user)
            return redirect('tienda')
        else:
            error_message = "Usuario o contraseña incorrectos"
            print(error_message)
            return render(request, 'login.html', {'error': error_message})

    return render(request, 'login.html')

def register(request):
    if request.user.is_authenticated:
        return redirect('tienda')
    if(request.method == 'POST'):
        Nombre = request.POST['nombre']
        Apellido = request.POST['apellido']
        Cedula = request.POST['cedula']
        Email = request.POST['email']
        Usuario = request.POST['username']
        Password = request.POST['password']
        
        error_message = None
        
        if not Nombre or not Apellido or not Cedula or not Email or not Usuario or not Password:
            error_message = "Debe llenar todos los campos"
            
        if User.objects.filter(username=Usuario).exists():
            error_message = "El usuario ya esta registrado por favor intente con otro"
        
        if User.objects.filter(email=Email).exists():
            error_message = "El email ya esta registrado por favor intente con otro"
        
        if Persona.objects.filter(Cedula=Cedula).exists():
            error_message = "La cedula ya esta registrada por favor intente con otra"
        
        if error_message:
            return render(request, 'registro.html', {'error': error_message})
        
        user = User.objects.create_user(Usuario, Email, Password)
        user.first_name = Nombre
        user.last_name = Apellido
        user.save()
        
        persona = Persona.objects.create(Nombre=Nombre, Apellido=Apellido, Cedula=Cedula, Email=Email, Usuario=user)
        persona.save()
        
        return redirect('login')
        
    return render(request, 'registro.html')

Parcial-2/HomeApp/views.py
from django.shortcuts import render, redirect

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        return redirect('tienda')
    return render(request, 'home.html', {})

def error_404_view(request, exception):
    return render(request, '404.html', {})

Parcial-2/TiendaApp/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Categoria, Producto

@login_required(login_url='/auth/login/')
def tienda(request):
    categorias = Categoria.objects.all()

    return render(request, 'inicio-tienda.html', { 'categorias': categorias })

@login_required(login_url='/auth/login/')
def producto(request, id):
    producto = get_object_or_404(Producto, id=id)

    return render(request, 'producto.html', { 'producto': producto })

@login_required(login_url='/auth/login/')
def categoria(request, id):
    categoria = get_object_or_404(Categoria, id=id)
    return render(request, 'categoria.html', { 'categoria': categoria })

Parcial-2/AuthApp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
</head>
<body>
    {% include 'layouts/Header.html' %}
    <main class="grid columns-2 grid-center m-20">
        <div class="col-center">
            <img src="{% static 'images/info.png' %}" alt="info">
        </div>
        <div class="col-center">
            <h2>Login</h2>
            <form action="{% url 'login' %}" method="POST" class="form">
                {% csrf_token %}
                <formfield class="single-field">
                    <label for="username">Usuario</label>
                    <input type="text" name="username" id="username" placeholder="Usuario" required>
                </formfield>
                <formfield class="single-field">
                    <label for="password">Contraseña</label>
                    <input type="password" name="password" id="password" placeholder="Contraseña" required>
                </formfield>
                <div class="button-group">
                    <button class="btn btn-primary">Autentificar</button>
                    <a class="btn btn-secondary"    href="{% url 'register' %}">Registrarse</a>
                </div>
            </form>
            {% include 'layouts/info.html' %}
        </div>
    </main>
    {% if error %}
    <div class="toast" id="toast" data-autohide="true">
        <div class="toast-info">
            <strong class="mr-auto">Error</strong>
            <p>{{ error }}</p>
        </div>
        <button type="button" class="close" data-dismiss="toast">&times;</button>
    </div>
    {% endif %}
</body>
<script>
    window.onload = function(){
        var toast = document.getElementById("toast");
        if(toast){
            toast.classList.add("show");
        }
    }

    close = document.getElementsByClassName("close")[0];
    close.onclick = function(){
        toast.style.display = "none";
    }
</script>
</html>

Parcial-2/AuthApp/templates/registro.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Registro</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
</head>
<body>
    {% include 'layouts/Header.html' %}
    <main class="grid columns-2 grid-center m-20">
        <div class="col-center">
            <h2>Registro</h2>
            <form  method="POST" action="{% url 'register' %}">
                {% csrf_token %}
                <formfield class="single-field">
                    <label for="nombre">Nombre</label>
                    <input type="text" name="nombre" id="nombre" placeholder="Jhon" required>
                </formfield>
                <formfield class="single-field">
                    <label for="apellido">Apellido</label>
                    <input type="text" name="apellido" id="apellido" placeholder="Doe" required>
                </formfield>
                <formfield class="single-field">
                    <label for="cedula">Cedula</label>
                    <input type="text" name="cedula" id="cedula" placeholder="1.193.121.459" required>
                </formfield>
                <formfield class="single-field">
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" placeholder="jhon@algo.otro" required>
                </formfield>
                <formfield class="multi-field">
                    <formfield class="single-field">
                        <label for="username">Usuario</label>
                        <input type="text" name="username" id="username" placeholder="Usuario" required>
                    </formfield>
                    <formfield class="single-field">
                        <label for="password">Contraseña</label>
                        <input type="password" name="password" id="password" placeholder="Contraseña" required>
                    </formfield>
                </formfield>
                <div class="button-group">
                    <button class="btn btn-primary">Registrar</button>
                    <a class="btn btn-secondary" href="{% url 'login' %}">Login</a>
                </div>
            </form>
        </div>
        <div class="col-center">
            <img src="{% static 'images/info.png' %}" alt="info">
            {% include 'layouts/info.html' %}
        </div>
    </main>
    {% if succes %}
        {% include 'layouts/modal.html' with title="Registro exitoso" message="Se ha registrado exitosamente" url="login" %}
    {% endif %}
    {% if error %}
        <div class="toast" id="toast" data-autohide="true">
            <div class="toast-info">
                <strong class="mr-auto">Error</strong>
                <p>{{ error }}</p>
            </div>
            <button type="button" class="close" data-dismiss="toast">&times;</button>
        </div>
    {% endif %}
</body>
<script>
    window.onload = function(){
        var toast = document.getElementById("toast");
        if(toast){
            toast.classList.add("show");
        }
    }

    close = document.getElementsByClassName("close")[0];
    close.onclick = function(){
        toast.style.display = "none";
    }
</script>
</html>

Parcial-2/TiendaApp/templates/categoria.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Categoria</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tienda-style.css' %}">
</head>
<body>
    {% include 'layouts/Header.html' %}
    <section class="categoria-view">
        <h1 class="categoria-title">{{ categoria.titulo }}</h1>
        <div class="categoria-container">
            {% for Producto in categoria.productos.all %}
                <a href="{% url 'producto' id=Producto.id %}" class="producto-link">
                    <article class="producto-container">
                        <div class="producto-img-container">
                            {% if Producto.imagenes.all %}
                                {% with random_image=Producto.imagenes.all|random %}
                                    <img src="{{ random_image.url }}" alt="{{ random_image.alt }}" class="producto-img">
                                {% endwith %}
                            {% else %}
                                <img src="{% static "images/no-image.jpg" %}" alt="No image" class="producto-img">
                            {% endif %}
                            <p class="producto-categoria">{{categoria.titulo}}</p>
                        </div>
                        <p class="producto-title">{{Producto.nombre}}</p>
                        <p class="producto-price">${{Producto.precio}}</p>
                    </article>
                </a>
            {% endfor %}
        </div>
    </section>
</body>

Parcial-2/TiendaApp/templates/inicio-tienda.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Tiendas</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tienda-style.css' %}">
</head>
<body>
    {% include 'layouts/Header.html' %}
    {% for categoria in categorias %}
        <section class="categoria-section">
            <div class="categoria-info">
                <p class="categoria-title">{{categoria.titulo}}</p>
                <a href="{% url 'categoria' id=categoria.id %}" class="btn outline">Ver mas</a>
            </div>
            <section class="categoria-container">
                {% for Producto in categoria.productos.all %}
                <a href="{% url 'producto' id=Producto.id %}" class="producto-link">
                        <article class="producto-container">
                            <div class="producto-img-container">
                                {% if Producto.imagenes.all %}
                                    {% with random_image=Producto.imagenes.all|random %}
                                        <img src="{{ random_image.url }}" alt="{{ random_image.alt }}" class="producto-img">
                                    {% endwith %}
                                {% else %}
                                    <img src="{% static "images/no-image.jpg" %}" alt="No image" class="producto-img">
                                {% endif %}
                                <p class="producto-categoria">{{categoria.titulo}}</p>
                            </div>
                            <p class="producto-title">{{Producto.nombre}}</p>
                            <p class="producto-price">${{Producto.precio}}</p>
                        </article>
                    </a>
                {% endfor %}
            </section>
        </section>
    {% endfor %}
</body>

Parcial-2/TiendaApp/templates/producto.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Producto</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tienda-style.css' %}">
</head>
<body>
    {% include 'layouts/Header.html' %}
    <section class="producto-view">
        <section class="producto-info">
            <h1> {{ producto.nombre }} </h1>
            <div class="producto-detalles">
                <p> Descripcion: <span> {{ producto.descripcion }} </span> </p>
                {% if producto.categoria_set.all %}
                    <p> Categorías:
                        {% for categoria in producto.categoria_set.all %}
                            <span>{{ categoria.titulo }}</span>
                        {% endfor %}
                    </p>
                {% endif %}
                <p> Precio: <span> {{ producto.precio }} </span> </p>
            </div>
            <div>
                <formfield class="single-field">
                    <label for="cantidad">Cantidad</label>
                    <input type="number" name="cantidad" id="cantidad" placeholder="0">
                </formfield>
                <button type="button" id="compra" class="outline primary">Comprar</button>
            </div>
        </section>
        <section class="product-images">
            <article class="image-container">
                <img id="main-image" src="{{ producto.imagenes.first.url }}" alt="Imagen del producto">
            </article>
            <div class="preview-container">
                {% for imagen in producto.imagenes.all %}
                    <img src="{{ imagen.url }}" class="preview-img" alt="{{ imagen.alt }}" onclick="cambiarImagen(this, '{{ imagen.url }}')">
                {% endfor %}
            </div>
        </section>
    </section>
    <div id="modal" class="modal" hidden>
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Exito</h4>
            </div>
            <div class="modal-body">
                <p>Compra Realizada Correctamente</p>
            </div>
            <div class="modal-footer">
                <a type="button" class="btn success" href="{% url 'tienda' %}">Aceptar</a>
            </div>
        </div>
    </div>
    <script>
        function cambiarImagen(elemento, url) {
            var miniaturas = document.querySelectorAll('.preview-img');
            miniaturas.forEach(function (miniatura) {
                miniatura.classList.remove('active');
            });

            elemento.classList.add('active');

            document.getElementById('main-image').src = url;
        }
        modal = document.querySelector('#modal');
        compra = document.querySelector('#compra');
        compra.addEventListener('click', function () {
            modal.removeAttribute('hidden');
            modal.style.display = 'block';
        });
    </script>
</body>
</html>

Parcial-2/templates/layouts/Header.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/general-style.css' %}">
<header>
    <nav>
        {% if user.is_authenticated or request.path == '/auth/register/' or request.path == '/auth/login/' %}
            <ul>
                {% if user.is_authenticated %}
                    <li><a class="btn primary" href="{% url 'tienda' %}">Inicio</a></li>
                {% else %}
                    <li><a class="btn primary" href="{% url 'home' %}">Inicio</a></li>
                {% endif %}
            </ul>
        {% else %}
            <a class="btn primary"  href="{% url 'login' %}">Login</a>
            <a class="btn outline primary" href="{% url 'register' %}">Register</a>
        {% endif %}
    </nav>

    <div class="right-content">
        <a href="#"><img src="{% static 'images/carrito.png' %}" alt="carrito"></a>
    </div>
</header>

Parcial-2/templates/layouts/info.html
{% load static %}
{% if user.is_authenticated %}
<div class="flex flex-row">
    <img src="{% static 'imgages/registro.png' %}" alt="registro">
    <div class="flex flex-column">
        <p>Nombre: <span>{{ user.nombre }}</span></p>
        <p>Apellido: <span>{{ user.apellido }}</span></p>
        <p>Cedula: <span>{{ user.cedula }}</span></p>
        <p>Correo: <span>{{ user.email }}</span></p>
    </div>
</div>
{% endif %}

Parcial-2/templates/layouts/modal.html
<div id="modal" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{title}}</h4>
        </div>
        <div class="modal-body">
            <p>{{modal.message}}</p>
        </div>
        <div class="modal-footer">
            <button id="modal-btn" type="button" class="btn btn-default btn-flat" data-dismiss="modal">Ok</button>
        </div>
    </div>
</div>